List Items = [
  {
    "Category": "Fruits",
    "Item": "Acai Berry",
    "teluguItem": "అకాయీ బెర్రీ",
    "Calories (kcal)": 56,
    "Protein (g)": 1.4,
    "Carbs (g)": 6,
    "Fat (g)": 3,
  },
  {
    "Category": "Fruits",
    "Item": "Apricot",
    "teluguItem": "ఆప్రికాట్",
    "Calories (kcal)": 48,
    "Protein (g)": 1.4,
    "Carbs (g)": 11,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Vegetables",
    "Item": "Potato",
    "teluguItem": "ఆలుగడ్డ",
    "Calories (kcal)": 77,
    "Protein (g)": 2,
    "Carbs (g)": 17,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Spinach",
    "teluguItem": "పాలకూర",
    "Calories (kcal)": 23,
    "Protein (g)": 2.9,
    "Carbs (g)": 3.6,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Vegetables",
    "Item": "Carrot",
    "teluguItem": "కారట్",
    "Calories (kcal)": 41,
    "Protein (g)": 0.9,
    "Carbs (g)": 10,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Brinjal",
    "teluguItem": "వంకాయ",
    "Calories (kcal)": 25,
    "Protein (g)": 1,
    "Carbs (g)": 6,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Cabbage",
    "teluguItem": "గోబి",
    "Calories (kcal)": 25,
    "Protein (g)": 1.3,
    "Carbs (g)": 6,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Apple",
    "teluguItem": "ఆపిల్",
    "Calories (kcal)": 52,
    "Protein (g)": 0.3,
    "Carbs (g)": 14,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Banana",
    "teluguItem": "అరటి పండు",
    "Calories (kcal)": 89,
    "Protein (g)": 1.1,
    "Carbs (g)": 23,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Orange",
    "teluguItem": "నారింజ",
    "Calories (kcal)": 47,
    "Protein (g)": 0.9,
    "Carbs (g)": 12,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Mango",
    "teluguItem": "మామిడి",
    "Calories (kcal)": 60,
    "Protein (g)": 0.8,
    "Carbs (g)": 15,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Papaya",
    "teluguItem": "బొప్పాయి",
    "Calories (kcal)": 43,
    "Protein (g)": 0.5,
    "Carbs (g)": 11,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Pomegranate",
    "teluguItem": "దానిమ్మ",
    "Calories (kcal)": 83,
    "Protein (g)": 1.7,
    "Carbs (g)": 19,
    "Fat (g)": 1.2,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Toor Dal",
    "teluguItem": "కందిపప్పు",
    "Calories (kcal)": 343,
    "Protein (g)": 22,
    "Carbs (g)": 62,
    "Fat (g)": 1.7,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Moong Dal",
    "teluguItem": "పెసరపప్పు",
    "Calories (kcal)": 347,
    "Protein (g)": 24,
    "Carbs (g)": 59,
    "Fat (g)": 1.2,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Chana Dal",
    "teluguItem": "సెనగపప్పు",
    "Calories (kcal)": 364,
    "Protein (g)": 19,
    "Carbs (g)": 61,
    "Fat (g)": 6,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Rajma",
    "teluguItem": "రాజ్మా",
    "Calories (kcal)": 333,
    "Protein (g)": 24,
    "Carbs (g)": 60,
    "Fat (g)": 1,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Black Chana",
    "teluguItem": "నల్ల సెనగలు",
    "Calories (kcal)": 360,
    "Protein (g)": 19,
    "Carbs (g)": 61,
    "Fat (g)": 6,
  },
  {
    "Category": "Groceries",
    "Item": "Rice",
    "teluguItem": "బియ్యం",
    "Calories (kcal)": 365,
    "Protein (g)": 7.1,
    "Carbs (g)": 80,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Groceries",
    "Item": "Wheat Flour",
    "teluguItem": "గోధుమ పిండి",
    "Calories (kcal)": 364,
    "Protein (g)": 12,
    "Carbs (g)": 76,
    "Fat (g)": 1.7,
  },
  {
    "Category": "Groceries",
    "Item": "Sugar",
    "teluguItem": "పంచదార",
    "Calories (kcal)": 387,
    "Protein (g)": 0,
    "Carbs (g)": 100,
    "Fat (g)": 0,
  },
  {
    "Category": "Groceries",
    "Item": "Cooking Oil",
    "teluguItem": "వంట నూనె",
    "Calories (kcal)": 884,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 100,
  },
  {
    "Category": "Groceries",
    "Item": "Ghee",
    "teluguItem": "నెయ్యి",
    "Calories (kcal)": 900,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 100,
  },
  {
    "Category": "Groceries",
    "Item": "Milk",
    "teluguItem": "పాలు",
    "Calories (kcal)": 42,
    "Protein (g)": 3.4,
    "Carbs (g)": 5,
    "Fat (g)": 1,
  },
  {
    "Category": "Veg Curries",
    "Item": "Paneer Butter Masala",
    "teluguItem": "పనీర్ బట్టర్ మసాలా",
    "Calories (kcal)": 320,
    "Protein (g)": 12,
    "Carbs (g)": 10,
    "Fat (g)": 25,
  },
  {
    "Category": "Veg Curries",
    "Item": "Vegetable Korma",
    "teluguItem": "కూరగాయల కుర్మా",
    "Calories (kcal)": 210,
    "Protein (g)": 5,
    "Carbs (g)": 18,
    "Fat (g)": 14,
  },
  {
    "Category": "Veg Curries",
    "Item": "Aloo Gobi",
    "teluguItem": "ఆలూ గోబీ",
    "Calories (kcal)": 180,
    "Protein (g)": 4,
    "Carbs (g)": 20,
    "Fat (g)": 8,
  },
  {
    "Category": "Veg Curries",
    "Item": "Dal Tadka",
    "teluguItem": "డాల్ తడ్కా",
    "Calories (kcal)": 190,
    "Protein (g)": 9,
    "Carbs (g)": 22,
    "Fat (g)": 7,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Chicken Curry",
    "teluguItem": "చికెన్ కూర",
    "Calories (kcal)": 240,
    "Protein (g)": 27,
    "Carbs (g)": 6,
    "Fat (g)": 14,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Mutton Curry",
    "teluguItem": "మటన్ కూర",
    "Calories (kcal)": 290,
    "Protein (g)": 25,
    "Carbs (g)": 5,
    "Fat (g)": 20,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Fish Curry",
    "teluguItem": "చేప కూర",
    "Calories (kcal)": 180,
    "Protein (g)": 22,
    "Carbs (g)": 4,
    "Fat (g)": 10,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Egg Curry",
    "teluguItem": "గుడ్డు కూర",
    "Calories (kcal)": 210,
    "Protein (g)": 13,
    "Carbs (g)": 3,
    "Fat (g)": 15,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Prawn Curry",
    "teluguItem": "రొయ్యల కూర",
    "Calories (kcal)": 200,
    "Protein (g)": 24,
    "Carbs (g)": 4,
    "Fat (g)": 10,
  },
  {
    "Category": "Vegetables",
    "Item": "Green Beans",
    "teluguItem": "ఆకుపచ్చ బీన్‌లు",
    "Calories (kcal)": 31,
    "Protein (g)": 2.1,
    "Carbs (g)": 7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Bitter Gourd",
    "teluguItem": "కారవేపల",
    "Calories (kcal)": 34,
    "Protein (g)": 2,
    "Carbs (g)": 7,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Fenugreek Leaves",
    "teluguItem": "మెంతులకూర",
    "Calories (kcal)": 49,
    "Protein (g)": 4.4,
    "Carbs (g)": 6,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Vegetables",
    "Item": "Bottle Gourd",
    "teluguItem": "సొరకాయ",
    "Calories (kcal)": 12,
    "Protein (g)": 0.6,
    "Carbs (g)": 3,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Ladyfinger",
    "teluguItem": "బెందకాయ",
    "Calories (kcal)": 33,
    "Protein (g)": 2,
    "Carbs (g)": 7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Ridge Gourd",
    "teluguItem": "పీసలకాయ",
    "Calories (kcal)": 18,
    "Protein (g)": 1,
    "Carbs (g)": 4,
    "Fat (g)": 0,
  },
  {
    "Category": "Vegetables",
    "Item": "Drumstick",
    "teluguItem": "సుగ్గిలక్కయ",
    "Calories (kcal)": 64,
    "Protein (g)": 2.1,
    "Carbs (g)": 12,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Cauliflower",
    "teluguItem": "గోబీ",
    "Calories (kcal)": 25,
    "Protein (g)": 2.8,
    "Carbs (g)": 5,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Pumpkin",
    "teluguItem": "గుమ్మడికాయ",
    "Calories (kcal)": 26,
    "Protein (g)": 1,
    "Carbs (g)": 6,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Radish",
    "teluguItem": "ముల్లంగి",
    "Calories (kcal)": 16,
    "Protein (g)": 0.6,
    "Carbs (g)": 3.4,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Beet Root",
    "teluguItem": "బీట్ రూట్",
    "Calories (kcal)": 43,
    "Protein (g)": 1.6,
    "Carbs (g)": 10,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Peas",
    "teluguItem": "బటానీలు",
    "Calories (kcal)": 81,
    "Protein (g)": 5.4,
    "Carbs (g)": 14,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Vegetables",
    "Item": "Cucumber",
    "teluguItem": "దోసకాయ",
    "Calories (kcal)": 16,
    "Protein (g)": 0.7,
    "Carbs (g)": 3.6,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Bell Pepper",
    "teluguItem": "మిర్చి",
    "Calories (kcal)": 31,
    "Protein (g)": 1,
    "Carbs (g)": 6,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Mushroom",
    "teluguItem": "పుట్టికుర",
    "Calories (kcal)": 22,
    "Protein (g)": 3.3,
    "Carbs (g)": 3.3,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Garlic",
    "teluguItem": "వెల్లుల్లి",
    "Calories (kcal)": 149,
    "Protein (g)": 6.4,
    "Carbs (g)": 33,
    "Fat (g)": 0.5,
  },
  {
    "Category": "Vegetables",
    "Item": "Ginger",
    "teluguItem": "అల్లం",
    "Calories (kcal)": 80,
    "Protein (g)": 1.8,
    "Carbs (g)": 18,
    "Fat (g)": 0.8,
  },
  {
    "Category": "Vegetables",
    "Item": "Green Chilli",
    "teluguItem": "పచ్చ మిర్చి",
    "Calories (kcal)": 40,
    "Protein (g)": 2,
    "Carbs (g)": 9,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Vegetables",
    "Item": "Coriander Leaves",
    "teluguItem": "కొత్తిమీర",
    "Calories (kcal)": 23,
    "Protein (g)": 2.1,
    "Carbs (g)": 3.7,
    "Fat (g)": 0.5,
  },
  {
    "Category": "Vegetables",
    "Item": "Mint Leaves",
    "teluguItem": "పుదీనా",
    "Calories (kcal)": 44,
    "Protein (g)": 3.8,
    "Carbs (g)": 8.4,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Vegetables",
    "Item": "Celery",
    "teluguItem": "సెలరీ",
    "Calories (kcal)": 16,
    "Protein (g)": 0.7,
    "Carbs (g)": 3.7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Leek",
    "teluguItem": "లీక్",
    "Calories (kcal)": 61,
    "Protein (g)": 1.5,
    "Carbs (g)": 14,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Turnip",
    "teluguItem": "టర్నిప్",
    "Calories (kcal)": 36,
    "Protein (g)": 1.1,
    "Carbs (g)": 8,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Zucchini",
    "teluguItem": "జుకీని",
    "Calories (kcal)": 17,
    "Protein (g)": 1.4,
    "Carbs (g)": 3.5,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Guava",
    "teluguItem": "జామ",
    "Calories (kcal)": 68,
    "Protein (g)": 2.6,
    "Carbs (g)": 14,
    "Fat (g)": 0.9,
  },
  {
    "Category": "Fruits",
    "Item": "Watermelon",
    "teluguItem": "పుచ్చకాయ",
    "Calories (kcal)": 30,
    "Protein (g)": 0.6,
    "Carbs (g)": 7.6,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Coconut",
    "teluguItem": "కొబ్బరి",
    "Calories (kcal)": 354,
    "Protein (g)": 3.3,
    "Carbs (g)": 15,
    "Fat (g)": 33,
  },
  {
    "Category": "Fruits",
    "Item": "Pineapple",
    "teluguItem": "అనాస",
    "Calories (kcal)": 50,
    "Protein (g)": 0.5,
    "Carbs (g)": 13,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Grapes",
    "teluguItem": "ద్రాక్ష",
    "Calories (kcal)": 67,
    "Protein (g)": 0.6,
    "Carbs (g)": 17,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Kiwi",
    "teluguItem": "కివీ",
    "Calories (kcal)": 61,
    "Protein (g)": 1.1,
    "Carbs (g)": 15,
    "Fat (g)": 0.5,
  },
  {
    "Category": "Fruits",
    "Item": "Mulberry",
    "teluguItem": "మూరిన్‌పండు",
    "Calories (kcal)": 43,
    "Protein (g)": 1.4,
    "Carbs (g)": 9,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Custard Apple",
    "teluguItem": "సీతాఫలం",
    "Calories (kcal)": 101,
    "Protein (g)": 1.6,
    "Carbs (g)": 25,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Jackfruit",
    "teluguItem": "పనసపండు",
    "Calories (kcal)": 95,
    "Protein (g)": 1.5,
    "Carbs (g)": 24,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Lemon",
    "teluguItem": "నిమ్మకాయ",
    "Calories (kcal)": 29,
    "Protein (g)": 1.1,
    "Carbs (g)": 9,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Lime",
    "teluguItem": "నిమ్మచెక్క",
    "Calories (kcal)": 30,
    "Protein (g)": 0.7,
    "Carbs (g)": 11,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Musk Melon",
    "teluguItem": "ముసుక్కా",
    "Calories (kcal)": 34,
    "Protein (g)": 0.8,
    "Carbs (g)": 8,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Strawberry",
    "teluguItem": "స్ట్రాబెర్రీ",
    "Calories (kcal)": 32,
    "Protein (g)": 0.8,
    "Carbs (g)": 7.7,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Blueberry",
    "teluguItem": "బ్లూబెర్రీ",
    "Calories (kcal)": 57,
    "Protein (g)": 0.7,
    "Carbs (g)": 14,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Raspberry",
    "teluguItem": "రాస్‌బెర్రీ",
    "Calories (kcal)": 52,
    "Protein (g)": 1.2,
    "Carbs (g)": 12,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Fruits",
    "Item": "Avocado",
    "teluguItem": "ఆవకాడో",
    "Calories (kcal)": 160,
    "Protein (g)": 2,
    "Carbs (g)": 9,
    "Fat (g)": 15,
  },
  {
    "Category": "Fruits",
    "Item": "Apricot",
    "teluguItem": "ఆప్రికాట్",
    "Calories (kcal)": 48,
    "Protein (g)": 1.4,
    "Carbs (g)": 11,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Date",
    "teluguItem": "ఖజూర",
    "Calories (kcal)": 282,
    "Protein (g)": 2.5,
    "Carbs (g)": 75,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Fig",
    "teluguItem": "అంజీర",
    "Calories (kcal)": 74,
    "Protein (g)": 0.8,
    "Carbs (g)": 19,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Urad Dal",
    "teluguItem": "మినుపప్పు",
    "Calories (kcal)": 341,
    "Protein (g)": 26,
    "Carbs (g)": 56,
    "Fat (g)": 0.6,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Masur Dal",
    "teluguItem": "ఎర్ర కందిపప్పు",
    "Calories (kcal)": 353,
    "Protein (g)": 25,
    "Carbs (g)": 60,
    "Fat (g)": 1.3,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Chickpeas",
    "teluguItem": "సెనగలు",
    "Calories (kcal)": 359,
    "Protein (g)": 19,
    "Carbs (g)": 63,
    "Fat (g)": 6,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Green Gram",
    "teluguItem": "పెసరపప్పు",
    "Calories (kcal)": 347,
    "Protein (g)": 24,
    "Carbs (g)": 62,
    "Fat (g)": 1.1,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "White Beans",
    "teluguItem": "తెల్లబీన్‌లు",
    "Calories (kcal)": 339,
    "Protein (g)": 24,
    "Carbs (g)": 61,
    "Fat (g)": 0.8,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Kidney Beans",
    "teluguItem": "కిడ్నీ బీన్‌లు",
    "Calories (kcal)": 333,
    "Protein (g)": 24,
    "Carbs (g)": 60,
    "Fat (g)": 1,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Pinto Beans",
    "teluguItem": "పింటో బీన్‌లు",
    "Calories (kcal)": 345,
    "Protein (g)": 15,
    "Carbs (g)": 62,
    "Fat (g)": 1.2,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Lentils",
    "teluguItem": "సోయాబీన్‌లు",
    "Calories (kcal)": 116,
    "Protein (g)": 9,
    "Carbs (g)": 20,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Soybean",
    "teluguItem": "సోయాబీన్‌లు",
    "Calories (kcal)": 446,
    "Protein (g)": 36,
    "Carbs (g)": 30,
    "Fat (g)": 20,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Peas (Dried)",
    "teluguItem": "ఎండిన బటానీలు",
    "Calories (kcal)": 364,
    "Protein (g)": 24,
    "Carbs (g)": 65,
    "Fat (g)": 1.1,
  },
  {
    "Category": "Groceries",
    "Item": "Bajra",
    "teluguItem": "సజ్జలు",
    "Calories (kcal)": 378,
    "Protein (g)": 11,
    "Carbs (g)": 67,
    "Fat (g)": 5,
  },
  {
    "Category": "Groceries",
    "Item": "Jowar",
    "teluguItem": "జొన్న",
    "Calories (kcal)": 329,
    "Protein (g)": 11,
    "Carbs (g)": 72,
    "Fat (g)": 3,
  },
  {
    "Category": "Groceries",
    "Item": "Ragi",
    "teluguItem": "రాగి",
    "Calories (kcal)": 328,
    "Protein (g)": 6.3,
    "Carbs (g)": 72,
    "Fat (g)": 1.3,
  },
  {
    "Category": "Groceries",
    "Item": "Maize",
    "teluguItem": "మొక్కజొన్న",
    "Calories (kcal)": 365,
    "Protein (g)": 9.4,
    "Carbs (g)": 74,
    "Fat (g)": 4.7,
  },
  {
    "Category": "Groceries",
    "Item": "Oats",
    "teluguItem": "ఓట్స్",
    "Calories (kcal)": 389,
    "Protein (g)": 17,
    "Carbs (g)": 66,
    "Fat (g)": 7,
  },
  {
    "Category": "Groceries",
    "Item": "Barley",
    "teluguItem": "గోధుమ",
    "Calories (kcal)": 354,
    "Protein (g)": 12,
    "Carbs (g)": 73,
    "Fat (g)": 2.3,
  },
  {
    "Category": "Groceries",
    "Item": "Buckwheat",
    "teluguItem": "కుట్టు పిండి",
    "Calories (kcal)": 343,
    "Protein (g)": 13,
    "Carbs (g)": 71,
    "Fat (g)": 3.4,
  },
  {
    "Category": "Groceries",
    "Item": "Millet",
    "teluguItem": "చిరుధాన్యాలు",
    "Calories (kcal)": 378,
    "Protein (g)": 6.2,
    "Carbs (g)": 76,
    "Fat (g)": 4.2,
  },
  {
    "Category": "Groceries",
    "Item": "Chickpea Flour",
    "teluguItem": "బెసన్ పిండి",
    "Calories (kcal)": 387,
    "Protein (g)": 20,
    "Carbs (g)": 68,
    "Fat (g)": 5,
  },
  {
    "Category": "Groceries",
    "Item": "Cornmeal",
    "teluguItem": "మొక్కజొన్న పిండి",
    "Calories (kcal)": 362,
    "Protein (g)": 8.6,
    "Carbs (g)": 76,
    "Fat (g)": 3.9,
  },
  {
    "Category": "Groceries",
    "Item": "Sesame Oil",
    "teluguItem": "నువ్వుల నూనె",
    "Calories (kcal)": 884,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 100,
  },
  {
    "Category": "Groceries",
    "Item": "Mustard Oil",
    "teluguItem": "ఆవ నూనె",
    "Calories (kcal)": 884,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 100,
  },
  {
    "Category": "Groceries",
    "Item": "Coconut Oil",
    "teluguItem": "కొబ్బరి నూనె",
    "Calories (kcal)": 892,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 99,
  },
  {
    "Category": "Groceries",
    "Item": "Butter",
    "teluguItem": "వెన్న",
    "Calories (kcal)": 717,
    "Protein (g)": 0.9,
    "Carbs (g)": 0.1,
    "Fat (g)": 81,
  },
  {
    "Category": "Groceries",
    "Item": "Yogurt",
    "teluguItem": "పెరుగు",
    "Calories (kcal)": 59,
    "Protein (g)": 3.5,
    "Carbs (g)": 4.7,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Groceries",
    "Item": "Paneer",
    "teluguItem": "పనీర్",
    "Calories (kcal)": 265,
    "Protein (g)": 25,
    "Carbs (g)": 3.6,
    "Fat (g)": 17,
  },
  {
    "Category": "Groceries",
    "Item": "Honey",
    "teluguItem": "తేనె",
    "Calories (kcal)": 304,
    "Protein (g)": 0.3,
    "Carbs (g)": 82,
    "Fat (g)": 0,
  },
  {
    "Category": "Groceries",
    "Item": "Jaggery",
    "teluguItem": "బెల్లం",
    "Calories (kcal)": 383,
    "Protein (g)": 0.4,
    "Carbs (g)": 95,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Groceries",
    "Item": "Salt",
    "teluguItem": "ఉప్పు",
    "Calories (kcal)": 0,
    "Protein (g)": 0,
    "Carbs (g)": 0,
    "Fat (g)": 0,
  },
  {
    "Category": "Groceries",
    "Item": "Cumin Seeds",
    "teluguItem": "జిలకర",
    "Calories (kcal)": 375,
    "Protein (g)": 17,
    "Carbs (g)": 43,
    "Fat (g)": 22,
  },
  {
    "Category": "Groceries",
    "Item": "Coriander Seeds",
    "teluguItem": "ధనియాలు",
    "Calories (kcal)": 298,
    "Protein (g)": 12,
    "Carbs (g)": 52,
    "Fat (g)": 17,
  },
  {
    "Category": "Groceries",
    "Item": "Turmeric Powder",
    "teluguItem": "పసుపు పొడి",
    "Calories (kcal)": 354,
    "Protein (g)": 7.8,
    "Carbs (g)": 65,
    "Fat (g)": 9.9,
  },
  {
    "Category": "Groceries",
    "Item": "Chili Powder",
    "teluguItem": "మిర్చి పొడి",
    "Calories (kcal)": 318,
    "Protein (g)": 14,
    "Carbs (g)": 56,
    "Fat (g)": 17,
  },
  {
    "Category": "Veg Curries",
    "Item": "Chana Masala",
    "teluguItem": "సెనగ మసాలా",
    "Calories (kcal)": 210,
    "Protein (g)": 12,
    "Carbs (g)": 24,
    "Fat (g)": 8,
  },
  {
    "Category": "Veg Curries",
    "Item": "Chokha",
    "teluguItem": "చోక్",
    "Calories (kcal)": 180,
    "Protein (g)": 6,
    "Carbs (g)": 20,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Sambar",
    "teluguItem": "సంబర్",
    "Calories (kcal)": 150,
    "Protein (g)": 8,
    "Carbs (g)": 18,
    "Fat (g)": 5,
  },
  {
    "Category": "Veg Curries",
    "Item": "Rasam",
    "teluguItem": "రసం",
    "Calories (kcal)": 120,
    "Protein (g)": 4,
    "Carbs (g)": 14,
    "Fat (g)": 4,
  },
  {
    "Category": "Veg Curries",
    "Item": "Baingan Bharta",
    "teluguItem": "వంకాయ చూర్ణం",
    "Calories (kcal)": 160,
    "Protein (g)": 5,
    "Carbs (g)": 16,
    "Fat (g)": 8,
  },
  {
    "Category": "Veg Curries",
    "Item": "Chole Bhature",
    "teluguItem": "చోలె భతూరా",
    "Calories (kcal)": 450,
    "Protein (g)": 18,
    "Carbs (g)": 50,
    "Fat (g)": 20,
  },
  {
    "Category": "Veg Curries",
    "Item": "Palak Paneer",
    "teluguItem": "పాలక్ పనీర్",
    "Calories (kcal)": 280,
    "Protein (g)": 15,
    "Carbs (g)": 12,
    "Fat (g)": 20,
  },
  {
    "Category": "Veg Curries",
    "Item": "Methi Aloo",
    "teluguItem": "మెంతులకూర ఆలూ",
    "Calories (kcal)": 160,
    "Protein (g)": 5,
    "Carbs (g)": 22,
    "Fat (g)": 6,
  },
  {
    "Category": "Veg Curries",
    "Item": "Bhindi Fry",
    "teluguItem": "బెందకాయ ఫ్రై",
    "Calories (kcal)": 140,
    "Protein (g)": 4,
    "Carbs (g)": 16,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Pumpkin Curry",
    "teluguItem": "గుమ్మడికాయ కూర",
    "Calories (kcal)": 130,
    "Protein (g)": 3,
    "Carbs (g)": 18,
    "Fat (g)": 5,
  },
  {
    "Category": "Veg Curries",
    "Item": "Green Bean Curry",
    "teluguItem": "ఆకుపచ్చ బీన్ కూర",
    "Calories (kcal)": 120,
    "Protein (g)": 5,
    "Carbs (g)": 14,
    "Fat (g)": 5,
  },
  {
    "Category": "Veg Curries",
    "Item": "Cauliflower 65",
    "teluguItem": "గోబీ 65",
    "Calories (kcal)": 220,
    "Protein (g)": 8,
    "Carbs (g)": 20,
    "Fat (g)": 12,
  },
  {
    "Category": "Veg Curries",
    "Item": "Mixed Vegetable Curry",
    "teluguItem": "మిశ్రమ కూరగాయ కూర",
    "Calories (kcal)": 150,
    "Protein (g)": 6,
    "Carbs (g)": 18,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Kidney Bean Curry",
    "teluguItem": "కిడ్నీ బీన్ కూర",
    "Calories (kcal)": 180,
    "Protein (g)": 12,
    "Carbs (g)": 20,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Carrot Fry",
    "teluguItem": "గాజర ఫ్రై",
    "Calories (kcal)": 130,
    "Protein (g)": 3,
    "Carbs (g)": 16,
    "Fat (g)": 6,
  },
  {
    "Category": "Veg Curries",
    "Item": "Bottle Gourd Curry",
    "teluguItem": "సొరకాయ కూర",
    "Calories (kcal)": 100,
    "Protein (g)": 3,
    "Carbs (g)": 12,
    "Fat (g)": 4,
  },
  {
    "Category": "Veg Curries",
    "Item": "Bitter Gourd Fry",
    "teluguItem": "కాకరకాయ వేపుడు",
    "Calories (kcal)": 140,
    "Protein (g)": 5,
    "Carbs (g)": 16,
    "Fat (g)": 6,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Butter Chicken",
    "teluguItem": "బట్టర్ చికెన్",
    "Calories (kcal)": 320,
    "Protein (g)": 28,
    "Carbs (g)": 8,
    "Fat (g)": 20,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Tandoori Chicken",
    "teluguItem": "తందూరీ చికెన్",
    "Calories (kcal)": 200,
    "Protein (g)": 35,
    "Carbs (g)": 3,
    "Fat (g)": 5,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Chettinad Chicken",
    "teluguItem": "చెట్టినాడ్ చికెన్",
    "Calories (kcal)": 280,
    "Protein (g)": 32,
    "Carbs (g)": 6,
    "Fat (g)": 14,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Goan Fish",
    "teluguItem": "గోవా చేప",
    "Calories (kcal)": 200,
    "Protein (g)": 26,
    "Carbs (g)": 4,
    "Fat (g)": 9,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Amritsari Kulcha",
    "teluguItem": "అమృతసర్ కుల్చా",
    "Calories (kcal)": 300,
    "Protein (g)": 10,
    "Carbs (g)": 35,
    "Fat (g)": 14,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Shrimp Masala",
    "teluguItem": "రొయ్యల మసాలా",
    "Calories (kcal)": 180,
    "Protein (g)": 26,
    "Carbs (g)": 5,
    "Fat (g)": 8,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Lamington",
    "teluguItem": "లామింగ్టన్",
    "Calories (kcal)": 380,
    "Protein (g)": 12,
    "Carbs (g)": 45,
    "Fat (g)": 18,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Goat Biryani",
    "teluguItem": "గోవర్దన బిర్యానీ",
    "Calories (kcal)": 380,
    "Protein (g)": 28,
    "Carbs (g)": 40,
    "Fat (g)": 15,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Duck Curry",
    "teluguItem": "బాతు కూర",
    "Calories (kcal)": 320,
    "Protein (g)": 32,
    "Carbs (g)": 5,
    "Fat (g)": 18,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Rabbit Curry",
    "teluguItem": "కుందేలు కూర",
    "Calories (kcal)": 240,
    "Protein (g)": 34,
    "Carbs (g)": 4,
    "Fat (g)": 10,
  },
  {
    "Category": "Vegetables",
    "Item": "Sweet Corn",
    "teluguItem": "తీపి మొక్కజొన్న",
    "Calories (kcal)": 86,
    "Protein (g)": 3.3,
    "Carbs (g)": 19,
    "Fat (g)": 1.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Artichoke",
    "teluguItem": "ఆర్టిచోక్",
    "Calories (kcal)": 47,
    "Protein (g)": 3.3,
    "Carbs (g)": 10,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Asparagus",
    "teluguItem": "ఆస్పరగస్",
    "Calories (kcal)": 20,
    "Protein (g)": 2.2,
    "Carbs (g)": 3.7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Bok Choy",
    "teluguItem": "బోక్ చోయ్",
    "Calories (kcal)": 13,
    "Protein (g)": 1.5,
    "Carbs (g)": 2.2,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Broccoli",
    "teluguItem": "బ్రోకోలీ",
    "Calories (kcal)": 34,
    "Protein (g)": 2.8,
    "Carbs (g)": 7,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Vegetables",
    "Item": "Brussels Sprouts",
    "teluguItem": "బ్రస్సెల్‌ స్ప్రાట్‌లు",
    "Calories (kcal)": 43,
    "Protein (g)": 3.4,
    "Carbs (g)": 9,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Chives",
    "teluguItem": "చైవ్‌లు",
    "Calories (kcal)": 30,
    "Protein (g)": 3.3,
    "Carbs (g)": 7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Kale",
    "teluguItem": "కేల్",
    "Calories (kcal)": 49,
    "Protein (g)": 4.3,
    "Carbs (g)": 9,
    "Fat (g)": 0.9,
  },
  {
    "Category": "Vegetables",
    "Item": "Okra",
    "teluguItem": "బెందకాయ",
    "Calories (kcal)": 33,
    "Protein (g)": 2,
    "Carbs (g)": 7,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Swiss Chard",
    "teluguItem": "సిల్వర్ బీట్",
    "Calories (kcal)": 19,
    "Protein (g)": 1.8,
    "Carbs (g)": 3.7,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Watercress",
    "teluguItem": "వాటర్‌క్రెస్",
    "Calories (kcal)": 11,
    "Protein (g)": 2.3,
    "Carbs (g)": 0.4,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Endive",
    "teluguItem": "ఎండివ్",
    "Calories (kcal)": 17,
    "Protein (g)": 1.3,
    "Carbs (g)": 3.4,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Arugula",
    "teluguItem": "అరుగుల",
    "Calories (kcal)": 25,
    "Protein (g)": 2.6,
    "Carbs (g)": 3.7,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Vegetables",
    "Item": "Eggplant",
    "teluguItem": "వంకాయ",
    "Calories (kcal)": 25,
    "Protein (g)": 1,
    "Carbs (g)": 6,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Kohlrabi",
    "teluguItem": "నూనె గడ్డ",
    "Calories (kcal)": 27,
    "Protein (g)": 1.7,
    "Carbs (g)": 6,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Parsnip",
    "teluguItem": "పార్స్‌నిప్",
    "Calories (kcal)": 75,
    "Protein (g)": 1.2,
    "Carbs (g)": 18,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Vegetables",
    "Item": "Rutabaga",
    "teluguItem": "రూటబాగా",
    "Calories (kcal)": 37,
    "Protein (g)": 1.2,
    "Carbs (g)": 8,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Squash",
    "teluguItem": "స్క్వాష్",
    "Calories (kcal)": 19,
    "Protein (g)": 1.4,
    "Carbs (g)": 3.5,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Daikon Radish",
    "teluguItem": "డెకన్ రాడిష్",
    "Calories (kcal)": 18,
    "Protein (g)": 0.6,
    "Carbs (g)": 4,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Vegetables",
    "Item": "Fennel",
    "teluguItem": "సోఫ",
    "Calories (kcal)": 31,
    "Protein (g)": 1.2,
    "Carbs (g)": 7,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Vegetables",
    "Item": "Jicama",
    "teluguItem": "జిక్‌మా",
    "Calories (kcal)": 38,
    "Protein (g)": 0.7,
    "Carbs (g)": 9,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Quince",
    "teluguItem": "కువిన్‌స్",
    "Calories (kcal)": 57,
    "Protein (g)": 0.4,
    "Carbs (g)": 15,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Tangerine",
    "teluguItem": "టాంజారిన్",
    "Calories (kcal)": 47,
    "Protein (g)": 0.7,
    "Carbs (g)": 12,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Clementine",
    "teluguItem": "క్లెమెంటైన్",
    "Calories (kcal)": 47,
    "Protein (g)": 0.7,
    "Carbs (g)": 12,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Blood Orange",
    "teluguItem": "రక్త నారింజ",
    "Calories (kcal)": 42,
    "Protein (g)": 0.8,
    "Carbs (g)": 11,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Passion Fruit",
    "teluguItem": "కృష్ణ ఫలం",
    "Calories (kcal)": 97,
    "Protein (g)": 2.2,
    "Carbs (g)": 23,
    "Fat (g)": 0.7,
  },
  {
    "Category": "Fruits",
    "Item": "Dragon Fruit",
    "teluguItem": "డ్రాగన్ ఫ్రూట్",
    "Calories (kcal)": 60,
    "Protein (g)": 1.2,
    "Carbs (g)": 13,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Rambutan",
    "teluguItem": "రాంబూటన్",
    "Calories (kcal)": 82,
    "Protein (g)": 0.8,
    "Carbs (g)": 21,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Lychee",
    "teluguItem": "లిచీ",
    "Calories (kcal)": 66,
    "Protein (g)": 0.8,
    "Carbs (g)": 17,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Blackberry",
    "teluguItem": "బ్లాక్‌బెర్రీ",
    "Calories (kcal)": 43,
    "Protein (g)": 1.4,
    "Carbs (g)": 10,
    "Fat (g)": 0.5,
  },
  {
    "Category": "Fruits",
    "Item": "Cranberry",
    "teluguItem": "క్రాన్‌బెర్రీ",
    "Calories (kcal)": 46,
    "Protein (g)": 0.4,
    "Carbs (g)": 12,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Boysenberry",
    "teluguItem": "బాయ్‌సెన్‌బెర్రీ",
    "Calories (kcal)": 66,
    "Protein (g)": 1.2,
    "Carbs (g)": 16,
    "Fat (g)": 0.4,
  },
  {
    "Category": "Fruits",
    "Item": "Elderberry",
    "teluguItem": "ఎల్డర్‌బెర్రీ",
    "Calories (kcal)": 73,
    "Protein (g)": 0.7,
    "Carbs (g)": 18,
    "Fat (g)": 0.5,
  },
  {
    "Category": "Fruits",
    "Item": "Goji Berry",
    "teluguItem": "గోజీ బెర్రీ",
    "Calories (kcal)": 368,
    "Protein (g)": 14,
    "Carbs (g)": 77,
    "Fat (g)": 15,
  },
  {
    "Category": "Fruits",
    "Item": "Acai Berry",
    "teluguItem": "అకాయీ బెర్రీ",
    "Calories (kcal)": 56,
    "Protein (g)": 1.4,
    "Carbs (g)": 6,
    "Fat (g)": 3,
  },
  {
    "Category": "Fruits",
    "Item": "Pear",
    "teluguItem": "పియర్",
    "Calories (kcal)": 57,
    "Protein (g)": 0.4,
    "Carbs (g)": 15,
    "Fat (g)": 0.1,
  },
  {
    "Category": "Fruits",
    "Item": "Peach",
    "teluguItem": "పీచ్",
    "Calories (kcal)": 39,
    "Protein (g)": 0.9,
    "Carbs (g)": 10,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Plum",
    "teluguItem": "బేరు",
    "Calories (kcal)": 46,
    "Protein (g)": 0.7,
    "Carbs (g)": 11,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Cherry",
    "teluguItem": "చెర్రీ",
    "Calories (kcal)": 63,
    "Protein (g)": 1.1,
    "Carbs (g)": 16,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Fruits",
    "Item": "Nectarine",
    "teluguItem": "నెక్టరిన్",
    "Calories (kcal)": 44,
    "Protein (g)": 1.1,
    "Carbs (g)": 11,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Fruits",
    "Item": "Cantaloupe",
    "teluguItem": "కాంటలూప్",
    "Calories (kcal)": 34,
    "Protein (g)": 0.8,
    "Carbs (g)": 8,
    "Fat (g)": 0.2,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Peanut",
    "teluguItem": "వేరుశనగ",
    "Calories (kcal)": 567,
    "Protein (g)": 26,
    "Carbs (g)": 16,
    "Fat (g)": 49,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Cashew Nut",
    "teluguItem": "జీడిపండు",
    "Calories (kcal)": 553,
    "Protein (g)": 18,
    "Carbs (g)": 30,
    "Fat (g)": 44,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Almond",
    "teluguItem": "బాదం",
    "Calories (kcal)": 579,
    "Protein (g)": 21,
    "Carbs (g)": 22,
    "Fat (g)": 50,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Walnut",
    "teluguItem": "అక్రోట్",
    "Calories (kcal)": 654,
    "Protein (g)": 15,
    "Carbs (g)": 14,
    "Fat (g)": 65,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Pistachio",
    "teluguItem": "పిస్తా",
    "Calories (kcal)": 562,
    "Protein (g)": 20,
    "Carbs (g)": 28,
    "Fat (g)": 45,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Hazelnut",
    "teluguItem": "హేజెల్‌నట్",
    "Calories (kcal)": 628,
    "Protein (g)": 15,
    "Carbs (g)": 17,
    "Fat (g)": 61,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Brazil Nut",
    "teluguItem": "బ్రెజిల్ నట్",
    "Calories (kcal)": 656,
    "Protein (g)": 14,
    "Carbs (g)": 12,
    "Fat (g)": 66,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Pecan",
    "teluguItem": "పీకాన్",
    "Calories (kcal)": 691,
    "Protein (g)": 9,
    "Carbs (g)": 14,
    "Fat (g)": 72,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Macadamia Nut",
    "teluguItem": "మక్‌కేడమియా నట్",
    "Calories (kcal)": 718,
    "Protein (g)": 8,
    "Carbs (g)": 14,
    "Fat (g)": 76,
  },
  {
    "Category": "Pulses & Legumes",
    "Item": "Pine Nut",
    "teluguItem": "పైన్ నట్",
    "Calories (kcal)": 673,
    "Protein (g)": 14,
    "Carbs (g)": 13,
    "Fat (g)": 68,
  },
  {
    "Category": "Groceries",
    "Item": "Rye Flour",
    "teluguItem": "రై పిండి",
    "Calories (kcal)": 335,
    "Protein (g)": 10,
    "Carbs (g)": 71,
    "Fat (g)": 2,
  },
  {
    "Category": "Groceries",
    "Item": "Semolina",
    "teluguItem": "రవ్వ",
    "Calories (kcal)": 360,
    "Protein (g)": 13,
    "Carbs (g)": 73,
    "Fat (g)": 1,
  },
  {
    "Category": "Groceries",
    "Item": "Poha",
    "teluguItem": "పోహ",
    "Calories (kcal)": 350,
    "Protein (g)": 8,
    "Carbs (g)": 76,
    "Fat (g)": 1,
  },
  {
    "Category": "Groceries",
    "Item": "Sabudana",
    "teluguItem": "సాబూదానా",
    "Calories (kcal)": 355,
    "Protein (g)": 0.2,
    "Carbs (g)": 88,
    "Fat (g)": 0.3,
  },
  {
    "Category": "Groceries",
    "Item": "Cream",
    "teluguItem": "క్రీమ్",
    "Calories (kcal)": 340,
    "Protein (g)": 2.3,
    "Carbs (g)": 2.8,
    "Fat (g)": 35,
  },
  {
    "Category": "Groceries",
    "Item": "Cottage Cheese",
    "teluguItem": "పనీర్",
    "Calories (kcal)": 98,
    "Protein (g)": 11,
    "Carbs (g)": 3.4,
    "Fat (g)": 5,
  },
  {
    "Category": "Groceries",
    "Item": "Mozzarella",
    "teluguItem": "మోజరెల్లా",
    "Calories (kcal)": 280,
    "Protein (g)": 28,
    "Carbs (g)": 3.1,
    "Fat (g)": 17,
  },
  {
    "Category": "Groceries",
    "Item": "Feta Cheese",
    "teluguItem": "ఫెటా చీజ్",
    "Calories (kcal)": 264,
    "Protein (g)": 14,
    "Carbs (g)": 4.1,
    "Fat (g)": 21,
  },
  {
    "Category": "Groceries",
    "Item": "Cheddar Cheese",
    "teluguItem": "చెడ్డర్ చీజ్",
    "Calories (kcal)": 403,
    "Protein (g)": 23,
    "Carbs (g)": 1.3,
    "Fat (g)": 33,
  },
  {
    "Category": "Groceries",
    "Item": "Almond Powder",
    "teluguItem": "బాదం పొడి",
    "Calories (kcal)": 579,
    "Protein (g)": 21,
    "Carbs (g)": 22,
    "Fat (g)": 50,
  },
  {
    "Category": "Veg Curries",
    "Item": "Ginger Potato",
    "teluguItem": "అల్లం ఆలూ",
    "Calories (kcal)": 170,
    "Protein (g)": 4,
    "Carbs (g)": 24,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Tomato Curry",
    "teluguItem": "టమాట కూర",
    "Calories (kcal)": 140,
    "Protein (g)": 3,
    "Carbs (g)": 16,
    "Fat (g)": 6,
  },
  {
    "Category": "Veg Curries",
    "Item": "Spinach Dal",
    "teluguItem": "పాలక్ డాల్",
    "Calories (kcal)": 200,
    "Protein (g)": 11,
    "Carbs (g)": 24,
    "Fat (g)": 7,
  },
  {
    "Category": "Veg Curries",
    "Item": "Mushroom Fry",
    "teluguItem": "పుట్టికుర ఫ్రై",
    "Calories (kcal)": 130,
    "Protein (g)": 6,
    "Carbs (g)": 14,
    "Fat (g)": 6,
  },
  {
    "Category": "Veg Curries",
    "Item": "Corn Curry",
    "teluguItem": "మొక్కజొన్న కూర",
    "Calories (kcal)": 160,
    "Protein (g)": 5,
    "Carbs (g)": 22,
    "Fat (g)": 6,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Tandoori Fish",
    "teluguItem": "తందూరీ చేప",
    "Calories (kcal)": 220,
    "Protein (g)": 32,
    "Carbs (g)": 3,
    "Fat (g)": 9,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Keema",
    "teluguItem": "కీమా",
    "Calories (kcal)": 280,
    "Protein (g)": 25,
    "Carbs (g)": 6,
    "Fat (g)": 18,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Nihari",
    "teluguItem": "నిహారీ",
    "Calories (kcal)": 320,
    "Protein (g)": 28,
    "Carbs (g)": 12,
    "Fat (g)": 18,
  },
  {
    "Category": "Non-Veg Curries",
    "Item": "Haleem",
    "teluguItem": "హలీమ్",
    "Calories (kcal)": 350,
    "Protein (g)": 24,
    "Carbs (g)": 30,
    "Fat (g)": 16,
  },
  // Junk Food Category
  {
    "Category": "Junk",
    "Item": "French Fries (Medium)",
    "teluguItem": "ఫ్రెంచ్ ఫ్రైస్",
    "Calories (kcal)": 320,
    "Protein (g)": 3.4,
    "Carbs (g)": 41,
    "Fat (g)": 15,
  },
  {
    "Category": "Junk",
    "Item": "Chocolate Bar",
    "teluguItem": "చాక్లెట్ బార్",
    "Calories (kcal)": 270,
    "Protein (g)": 4,
    "Carbs (g)": 28,
    "Fat (g)": 15,
  },
  {
    "Category": "Junk",
    "Item": "Vanilla Cake Slice",
    "teluguItem": "వెనిల్లా కేక్",
    "Calories (kcal)": 280,
    "Protein (g)": 2.5,
    "Carbs (g)": 42,
    "Fat (g)": 11,
  },
  {
    "Category": "Junk",
    "Item": "Chocolate Cake Slice",
    "teluguItem": "చాక్లెట్ కేక్",
    "Calories (kcal)": 310,
    "Protein (g)": 3,
    "Carbs (g)": 42,
    "Fat (g)": 14,
  },
  {
    "Category": "Junk",
    "Item": "Donut",
    "teluguItem": "డోనట్",
    "Calories (kcal)": 250,
    "Protein (g)": 3,
    "Carbs (g)": 33,
    "Fat (g)": 12,
  },
  {
    "Category": "Junk",
    "Item": "Pastry",
    "teluguItem": "పేస్ట్రీ",
    "Calories (kcal)": 230,
    "Protein (g)": 2.5,
    "Carbs (g)": 30,
    "Fat (g)": 11,
  },
  {
    "Category": "Junk",
    "Item": "Croissant",
    "teluguItem": "క్రీసెంట్",
    "Calories (kcal)": 240,
    "Protein (g)": 3.5,
    "Carbs (g)": 27,
    "Fat (g)": 13,
  },
  {
    "Category": "Junk",
    "Item": "Cookies (2 pieces)",
    "teluguItem": "కుకీలు",
    "Calories (kcal)": 200,
    "Protein (g)": 2.5,
    "Carbs (g)": 26,
    "Fat (g)": 10,
  },
  {
    "Category": "Junk",
    "Item": "Instant Noodles (Cooked)",
    "teluguItem": "తక్షణ నూడిల్స్",
    "Calories (kcal)": 190,
    "Protein (g)": 5,
    "Carbs (g)": 28,
    "Fat (g)": 5,
  },
  {
    "Category": "Junk",
    "Item": "Gulab Jamun (2 pieces)",
    "teluguItem": "గులాబ్ జామున్",
    "Calories (kcal)": 290,
    "Protein (g)": 2,
    "Carbs (g)": 46,
    "Fat (g)": 11,
  },
  {
    "Category": "Junk",
    "Item": "Rasgulla (2 pieces)",
    "teluguItem": "రాస్‌గుల్లా",
    "Calories (kcal)": 220,
    "Protein (g)": 2.5,
    "Carbs (g)": 42,
    "Fat (g)": 3,
  },
  {
    "Category": "Junk",
    "Item": "Jalebi (100g)",
    "teluguItem": "జలేబీ",
    "Calories (kcal)": 330,
    "Protein (g)": 0.5,
    "Carbs (g)": 82,
    "Fat (g)": 1,
  },
  {
    "Category": "Junk",
    "Item": "Laddu",
    "teluguItem": "లడ్డు",
    "Calories (kcal)": 280,
    "Protein (g)": 4,
    "Carbs (g)": 34,
    "Fat (g)": 14,
  },
  {
    "Category": "Junk",
    "Item": "Barfi (Milk Fudge)",
    "teluguItem": "బర్ఫీ",
    "Calories (kcal)": 300,
    "Protein (g)": 5,
    "Carbs (g)": 36,
    "Fat (g)": 15,
  },
  {
    "Category": "Junk",
    "Item": "Halwa (100g)",
    "teluguItem": "హలవా",
    "Calories (kcal)": 380,
    "Protein (g)": 3,
    "Carbs (g)": 48,
    "Fat (g)": 19,
  },
  {
    "Category": "Junk",
    "Item": "Kheer (Dessert)",
    "teluguItem": "ఖీర్",
    "Calories (kcal)": 240,
    "Protein (g)": 4,
    "Carbs (g)": 32,
    "Fat (g)": 10,
  },
  {
    "Category": "Junk",
    "Item": "Biriyani (1 plate)",
    "teluguItem": "బిర్యానీ",
    "Calories (kcal)": 450,
    "Protein (g)": 25,
    "Carbs (g)": 48,
    "Fat (g)": 18,
  },
  {
    "Category": "Junk",
    "Item": "Burger (Regular)",
    "teluguItem": "బర్గర్",
    "Calories (kcal)": 540,
    "Protein (g)": 28,
    "Carbs (g)": 41,
    "Fat (g)": 28,
  },
  {
    "Category": "Junk",
    "Item": "Pizza Slice",
    "teluguItem": "పిజ్జా",
    "Calories (kcal)": 285,
    "Protein (g)": 12,
    "Carbs (g)": 36,
    "Fat (g)": 10,
  },
  {
    "Category": "Junk",
    "Item": "Samosa (1 piece)",
    "teluguItem": "సమోసా",
    "Calories (kcal)": 260,
    "Protein (g)": 3,
    "Carbs (g)": 28,
    "Fat (g)": 14,
  },
  {
    "Category": "Junk",
    "Item": "Pakora (100g)",
    "teluguItem": "పకోడా",
    "Calories (kcal)": 290,
    "Protein (g)": 4,
    "Carbs (g)": 32,
    "Fat (g)": 15,
  },
  {
    "Category": "Junk",
    "Item": "Potato Chips (Bag)",
    "teluguItem": "చిప్‌లు",
    "Calories (kcal)": 520,
    "Protein (g)": 5,
    "Carbs (g)": 52,
    "Fat (g)": 32,
  },
  {
    "Category": "Junk",
    "Item": "Cheetos (Bag)",
    "teluguItem": "చీటోస్",
    "Calories (kcal)": 540,
    "Protein (g)": 4,
    "Carbs (g)": 54,
    "Fat (g)": 34,
  },
  {
    "Category": "Junk",
    "Item": "Corn Flakes Bowl",
    "teluguItem": "కార్న్ ఫ్లేక్‌లు",
    "Calories (kcal)": 150,
    "Protein (g)": 3,
    "Carbs (g)": 34,
    "Fat (g)": 1,
  },
  {
    "Category": "Junk",
    "Item": "Soft Drink (200ml)",
    "teluguItem": "సాఫ్ట్ డ్రింక్",
    "Calories (kcal)": 85,
    "Protein (g)": 0,
    "Carbs (g)": 21,
    "Fat (g)": 0,
  },
  {
    "Category": "Junk",
    "Item": "Ice Cream Scoop",
    "teluguItem": "ఐస్ క్రీమ్",
    "Calories (kcal)": 135,
    "Protein (g)": 2,
    "Carbs (g)": 19,
    "Fat (g)": 6,
  },
  {
    "Category": "Junk",
    "Item": "Fried Egg Puff",
    "teluguItem": "ఎగ్ పఫ్",
    "Calories (kcal)": 320,
    "Protein (g)": 10,
    "Carbs (g)": 25,
    "Fat (g)": 20,
  },
  {
    "Category": "Junk",
    "Item": "Chow Mein",
    "teluguItem": "చౌ మీన్",
    "Calories (kcal)": 420,
    "Protein (g)": 12,
    "Carbs (g)": 52,
    "Fat (g)": 18,
  },
  {
    "Category": "Junk",
    "Item": "Momos (5 pieces)",
    "teluguItem": "మోమోస్",
    "Calories (kcal)": 280,
    "Protein (g)": 8,
    "Carbs (g)": 42,
    "Fat (g)": 8,
  },
];
